name: CI - Ingestion and dbt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ingestion_and_dbt:
    runs-on: ubuntu-latest

    env:
      # Pass Snowflake secrets into environment variables
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

      # Let dbt find the profiles file inside the repo
      DBT_PROFILES_DIR: ${{ github.workspace }}/dbt_profiles

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas faker python-dateutil
          pip install "snowflake-connector-python[pandas]" python-dotenv
          pip install dbt-core dbt-snowflake
          pip install pytest

      - name: Generate mock data CSVs
        run: |
          python ingestion/python/generate_mock_data.py

      - name: Run Python tests (pytest)
        run: |
          pytest

      - name: Load RAW data into Snowflake
        run: |
          python ingestion/python/load_raw_to_snowflake.py

      - name: dbt debug
        working-directory: dbt_project
        run: |
          dbt debug

      - name: dbt run
        working-directory: dbt_project
        run: |
          dbt run

      - name: dbt test
        working-directory: dbt_project
        run: |
          dbt test
